apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-springboot-simple-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-springboot-simple-web
  template:
    metadata:
      labels:
        app: demo-springboot-simple-web
    spec:
      containers:
        - name: demo-springboot-simple-web
          image: kajundrama/demo-springboot-simple-web:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always