apiVersion: v1
kind: Service
metadata:
  name: demo-springboot-simple-web
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: demo-springboot-simple-web
  type: NodePort